<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Keep what customers ask the assistant.
 *
 * Until now the transcript lived only in the shopper's sessionStorage and the
 * server kept nothing, so the store had no way to see the questions being asked
 * — which sizes people want, what they cannot find, where the assistant gives
 * up. Those are the queries the owner asked to be able to read.
 *
 * Two tables rather than a JSON blob on one, because the browser only ever
 * sends the last few turns: each request appends the new pair, so a long
 * conversation is kept whole even as the window the client sends slides.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('assistant_conversations', function (Blueprint $table) {
            $table->id();
            // Generated by the widget, one per chat session; the server never
            // trusts it for anything but grouping.
            $table->string('uid', 64)->unique();
            $table->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();
            // The same two-year cookie visits and abandoned carts key on, so a
            // conversation can be tied to the rest of that person's session.
            $table->string('visitor_token', 64)->nullable()->index();
            $table->string('first_page', 200)->nullable();
            $table->string('last_page', 200)->nullable();
            $table->string('ua', 255)->nullable();
            $table->unsignedInteger('message_count')->default(0);
            // Whether the assistant failed to answer at least once here — the
            // fastest way to find the conversations worth reading.
            $table->boolean('had_failure')->default(false);
            $table->timestamp('last_message_at')->nullable()->index();
            $table->timestamps();
        });

        Schema::create('assistant_messages', function (Blueprint $table) {
            $table->id();
            $table->foreignId('assistant_conversation_id')->constrained()->cascadeOnDelete();
            $table->string('role', 12);                 // user | assistant
            $table->text('content');
            // The product cards the reply carried, so the log shows what was
            // actually put in front of her.
            $table->json('products')->nullable();
            $table->boolean('ok')->default(true);
            $table->timestamp('created_at')->nullable();

            $table->index(['assistant_conversation_id', 'id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('assistant_messages');
        Schema::dropIfExists('assistant_conversations');
    }
};
